name: Build CI

on:
  push:
    branches: ["dev"]

defaults:
  run:
    working-directory: /var/www/portfolio_dev

jobs:
  develop:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: "Run Commands"
        run: |
          pwd
          git checkout dev
          git branch
          node -v
      - name: "Install Dependencies"
        run: yarn
      - name: "Build for production"
        run: yarn build
